vim.keymap.set("n", "<CR>", ":nohlsearch<CR>", { silent = true })
vim.keymap.set("n", "<leader>r<space>", "mm:%s/[\t ]*$//g<CR>:noh<CR>'mzz", {})
vim.keymap.set("n", "<leader>n", ":noh<cr>", {})
vim.keymap.set("n", "<leader>w", ":w!<cr>", {})
vim.keymap.set("n", "<leader>o", ":Oil<cr>", {})
vim.keymap.set("n", "<leader>p", ":FzfLua files<cr>", {})
vim.keymap.set("n", "<leader>co", ":copen<cr>", {})
vim.keymap.set("n", "<leader>cn", ":cnext<cr>", {})
vim.keymap.set("n", "<leader>cp", ":cprev<cr>", {})
vim.keymap.set("n", "<leader>Rs", function()
    require("kulala").run()
end, {})
vim.keymap.set("n", "<leader>Ra", function()
    require("kulala").run_all()
end, {})
vim.keymap.set("n", "<leader>Rr", function()
    require("kulala").replay()
end, {})
vim.keymap.set("n", "<leader>Rb", function()
    require("kulala").scratchpad()
end, {})

vim.keymap.set("v", "<C-c>", '"+ygv', {})
vim.keymap.set("t", "<leader><esc>", "<C-\\><C-n>", {})

local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, opts)
vim.keymap.set("n", "[d", function() vim.diagnostic.jump({ count = -1, float = true }) end, opts)
vim.keymap.set("n", "]d", function() vim.diagnostic.jump({ count = 1, float = true }) end, opts)
vim.keymap.set("n", "<leader>q", vim.diagnostic.setqflist, opts)
