vim.keymap.set("n", "<silent><CR>", ":nohlsearch<CR>", {})
vim.keymap.set("n", "<leader>r<space>", "mm:%s/[\t ]*$//g<CR>:noh<CR>'mzz", {})
vim.keymap.set("n", "<leader>n", ":noh<cr>", {})
vim.keymap.set("n", "<leader>w", ":w!<cr>", {})
vim.keymap.set("n", "<leader>o", ":Oil<cr>", {})
vim.keymap.set("n", "<leader>p", ":FzfLua files<cr>", {})
vim.keymap.set("n", "<leader>cp", ":Copilot enable<cr>", {})
vim.keymap.set("n", "<leader>co", ":copen<cr>", {})
vim.keymap.set("n", "<leader>cn", ":cnext<cr>", {})
vim.keymap.set("n", "<leader>cp", ":cprev<cr>", {})
vim.keymap.set("n", "<leader>Rs", function()
    require("kulala").run()
end, {})
vim.keymap.set("n", "<leader>Ra", function()
    require("kulala").run_all()
end, {})
vim.keymap.set("n", "<leader>Rr", function()
    require("kulala").replay()
end, {})
vim.keymap.set("n", "<leader>Rb", function()
    require("kulala").scratchpad()
end, {})

vim.keymap.set("v", "<C-c>", '"+ygv', {})
vim.keymap.set("t", "<leader><esc>", "<C-\\><C-n>", {})
vim.keymap.set("i", "<C-l>", 'copilot#Accept("\\<CR>")', { expr = true, replace_keycodes = false })

local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, opts)
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
vim.keymap.set("n", "<leader>q", vim.diagnostic.setqflist, opts)
