require('mini.icons').setup()
require('mini.completion').setup()
require('mini.surround').setup()
require('mini.pairs').setup()
require('mini.diff').setup()
require('mini.notify').setup()
require('mini.ai').setup()
require('mini.operators').setup()
